# Generated by Django 4.1 on 2023-12-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "bcode",
                    models.IntegerField(
                        db_column="BCODE", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="TITLE", max_length=200)),
                (
                    "author",
                    models.CharField(
                        blank=True, db_column="AUTHOR", max_length=20, null=True
                    ),
                ),
                (
                    "year_of_publication",
                    models.CharField(
                        blank=True,
                        db_column="YEAR-OF-PUBLICATION",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, db_column="PRICE", null=True),
                ),
            ],
            options={
                "db_table": "book_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BookStore",
            fields=[
                (
                    "bscode",
                    models.IntegerField(
                        db_column="BSCODE", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=100)),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="TEL", max_length=15, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="COUNTRY", max_length=20, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="CITY", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "book_store",
                "managed": False,
            },
        ),
    ]
